# This workflow runs CI checks for the Just Natsuki DDLC mod
name: Gen Contributors

on:
  #For now, we only run when specified
  workflow_dispatch:

jobs:
    get_contributors:
        runs-on: ubuntu-latest
        name: A job to automate contrib in readme
        steps:
            - name: Contribute List
              uses: akhilmhdh/contributors-readme-action@v2.3.4
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
